services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    env_file:
      - ./.env.example
    depends_on:
      db:
        condition: service_healthy
    command: /bin/bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - dev_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["pnpm", "dev"]

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./.env.example
    ports:
      - "5432:5432"
    volumes:
        - dev_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U albins_dev" ]
      interval: 1s
      retries: 5
      timeout: 3s

  nginx:
    image: nginx:alpine3.20
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./yxorp/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./backend/static:/app/static
      - ./backend/media:/app/media

volumes:
    dev_pgdata:
    dev_node_modules:
